#!/bin/bash

# Executa o executável original e armazena a saída
output=$(./inversaAux)

# Verifica se o programa 'inversaAux' foi executado com sucesso
if [ $? -eq 0 ]; then
    # Exibe a saída do programa
    echo "$output"
    
    # Executa o LIKWID com o grupo 'FLOPS_AVX' e exibe os contadores específicos
    echo "$output" | likwid-perfctr -C 0 -g FLOPS_DP --force -e FP_ARITH_INST_RETIRED_SCALAR_DOUBLE,DP | grep -E "FP_ARITH_INST_RETIRED_SCALAR_DOUBLE|DP \[MFLOP/s\]"
else
    echo "Erro: O programa inversa falhou ao executar."
fi
